### ISSUE TITLE
external link inherits ?stage=Stage from page

### ISSUE THREAD

**Issue by xini** [fromholdio/silverstripe-superlinker#4]
When you create an external link and view the page with ?stage=Stage, the link includes the stage parameter as well, which results in an error when following the link to some external sites.

**Comment by xini** [comment]
I had fixed that one in https://github.com/fromholdio/silverstripe-superlinker/commit/f6cb5d81b79998bbfde8178ab6369d9f2e4dccd4, but it looks like it's back...

**Comment by xini** [comment]
can you have another look into this, please?

**Comment by dizzystuff** [comment]
Hey @xini this is resolved and tagged as 2.1.5.

So `Versioned` has a `VersionedStateExtension` that applies to DataObjects and listens for an `updateLink` extension hook, and when present, it applies the version information to the query string. That's where it coming from / how it's getting there. 

SuperLinker uses the same name for its `Link()` extension hook, and so this is getting caught up in it. At a later point we can look at changing the extension hook in SuperLinker, and choose to apply Versioned state information to a link within individual link extension classes (ie SiteTree/File). 

For the timebeing, by overriding the value of $link in the hook, it effectively removes the state info from query string. I'll try and not commit over the top of this change this time 😅 

If it remains an intermittent issue even with this fix, it could be config.yml priority problems - we should try applying the extensions via config.yml (rather than in-class as is currently) and ensuring that they then run after `versionedstate` config.
